version = 1
# Snapshotter's own home directory where it stores and creates necessary resources
root = "/var/lib/containerd-nydus"
# The snapshotter's GRPC server socket, containerd will connect to plugin on this socket
address = "/run/containerd-nydus/containerd-nydus-grpc.sock"
daemon_mode = "multiple"
# Snapshotter's debug and trace HTTP server interface
enable_system_controller = true
# Enable by assigning an address, empty indicates metrics server is disabled
metrics_address = ":9110"
# Whether tp enable stargz support
enable_stargz = false
# Whether snapshotter should try to clean up resources when it is closed
cleanup_on_close = false

[daemon]
nydusd_path = "/usr/local/bin/nydusd"
nydusimage_path = "/usr/local/bin/nydus-image"
# fusedev or fscache
fs_driver = "fusedev"
# Specify nydusd log level
log_level = "info"
# How to process when daemon dies: "none", "restart" or "failover"
recover_policy = "restart"
# Specify a configuration file for nydusd
nydusd_config = "/etc/nydus/config.json"
# The fuse or fscache IO working threads started by nydusd
threads_number = 4

[log]
# Snapshotter's log level
level = "info"
log_rotation_compress = true
log_rotation_local_time = true
# Max number of days to retain logs
log_rotation_max_age = 7
log_rotation_max_backups = 5
# In unit MB(megabytes)
log_rotation_max_size = 1
log_to_stdout = false

[remote]
convert_vpc_registry = false

[remote.auth]
# Fetch the pricate registry auth by listening to K8s API server
enable_kubeconfig_keychain = false
# synchronize `kubernetes.io/dockerconfigjson` secret from kubernetes API server with specified kubeconfig (default `$KUBECONFIG` or `~/.kube/config`)
kubeconfig_path = ""
# Fetch the private regsitry auth as CRI image service proxy
enable_cri_keychain = false
# the target image service when using image proxy
image_service_address = ""

[snapshot]
enable_nydus_overlayfs = false
# Whether to remove resources when a snapshot is removed
sync_remove = false

[cache_manager]
disable = false
gc_period = "24h"
cache_dir = ""

[image]
public_key_file = ""
validate_signature = false
